services:
  backend:
    build: .
    container_name: inventory-backend
    environment:
      DB_HOST: inventory-db.cz0iyics2f29.ap-south-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_SSLMODE: require
    ports:
      - "8080:8080"
